# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-02 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user', models.EmailField(max_length=254, unique=True)),
                ('last_accessed', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_ordered', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('total_ordered', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('address_line1', models.CharField(max_length=254)),
                ('address_line2', models.CharField(max_length=254)),
                ('pincode', models.CharField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_db.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('phone_type', models.CharField(max_length=6)),
                ('is_reachable', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_db.User')),
            ],
        ),
    ]
